# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160213_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youvid',
            field=models.URLField(blank=True, default='http://www.youtube.com'),
        ),
    ]
